### ISSUE TITLE
Finish the exercises

### ISSUE THREAD

**Issue by ghost** [Fubukiis/react-tutorial-ts-impl#1]
## What
Finish all the exercises provided at the last part of the tutorial

## Todos

- [x] Display the location for each move in the format (col, row) in the move history list.
- [x] Bold the currently selected item in the move list.
- [x] Rewrite Board to use two loops to make the squares instead of hardcoding them.
- [ ] Add a toggle button that lets you sort the moves in either ascending or descending order.
- [ ] When someone wins, highlight the three squares that caused the win.
- [ ] When no one wins, display a message about the result being a draw.
